### ISSUE TITLE
Babashka compatibility

### ISSUE THREAD

**Issue by serioga** [strojure/parsesso#1]
Same issue as in kern https://github.com/blancas/kern/pull/21/files reported by @borkdude

In the repo, you can try with:

    $ bb -cp src -e "(require '[strojure.parsesso.core :as p])"

**Comment by borkdude** [comment]
This is not a bug imo, just a nice to have for bb compatibility :) Thank you for considering.

**Comment by serioga** [comment]
@borkdude at least if I decided to make _cross-platform_ library and `bb` is one of the platforms...

**Comment by serioga** [comment]
@borkdude What should I to do with `IFn` interface here?
https://github.com/strojure/parsesso/blob/3c92c4ad7f5f2234b01c391ef099866311fa4d54/src/strojure/parsesso/impl/parser.cljc#L10

**Comment by serioga** [comment]
Now the command `$ bb -cp src -e "(require '[strojure.parsesso.core :as p])"` executes without errors.

**Comment by borkdude** [comment]
Awesome! I hope it wasn't too painful.

**Comment by serioga** [comment]
It was not painful but this question is still open https://github.com/strojure/parsesso/issues/1#issuecomment-1273615677

It's not always possible just throw problematic code away :-)

**Comment by borkdude** [comment]
I thought you already solved the issue with IFn

**Comment by serioga** [comment]
I solved here by removing code, but I have no idea what to do when I really need to extend IFn for any reason.

**Comment by borkdude** [comment]
@serioga 

In bb it's currently not possible to extend deftype or defrecord to IFn, but `reify` does work. This comes from restrictions in  graalvm native image where it's not possible to create new JVM types on the fly. Some of the most frequent patterns have to be hardcoded beforehand (which is currently done for `reify`). I'm considering support IFn for `defrecord` in the future since that seems pretty common. But in general, just using hash-maps with functions works, also in Clojure.
